// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from erc20.djinni

#import <Foundation/Foundation.h>

/**Representation of ERC20Tokens */
@interface LGERC20Token : NSObject
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                              symbol:(nonnull NSString *)symbol
                     contractAddress:(nonnull NSString *)contractAddress
                     numberOfDecimal:(int32_t)numberOfDecimal;
+ (nonnull instancetype)ERC20TokenWithName:(nonnull NSString *)name
                                    symbol:(nonnull NSString *)symbol
                           contractAddress:(nonnull NSString *)contractAddress
                           numberOfDecimal:(int32_t)numberOfDecimal;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSString * symbol;

@property (nonatomic, readonly, nonnull) NSString * contractAddress;

@property (nonatomic, readonly) int32_t numberOfDecimal;

@end
