// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from erc20.djinni

#import "LGERC20Token.h"
#import <Foundation/Foundation.h>
@class LGBigInt;
@class LGERC20LikeOperation;


/**ERC20-like accounts class */
@interface LGERC20LikeAccount : NSObject

- (nonnull LGERC20Token *)getToken;

- (nonnull NSString *)getAddress;

- (nullable LGBigInt *)getBalance;

- (nonnull NSArray<LGERC20LikeOperation *> *)getOperations;

@end
