// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import <Foundation/Foundation.h>
@class LGAmount;
@class LGEthereumLikeAddress;


/**Class representing a Ethereum transaction */
@interface LGEthereumLikeTransaction : NSObject

/** Get the hash of the transaction. */
- (nonnull NSString *)getHash;

/** Get the nonce of the transaction : sequence number issued by originating EOA */
- (int32_t)getNonce;

/** Get Gas price (in wei) */
- (nullable LGAmount *)getGasPrice;

/** Get start gas (in wei) : maximum amount of gas the originator is willing to pay */
- (nullable LGAmount *)getGasLimit;

/** Get destination ETH address */
- (nullable LGEthereumLikeAddress *)getReceiver;

/** Get amount of ether to send */
- (nullable LGAmount *)getValue;

/** Get binary data payload */
- (nullable NSData *)getData;

/** Serialize the transaction to its raw format. */
- (nonnull NSData *)serialize;

/**
 * Get the time when the transaction was issued or the time of the block including
 * this transaction
 */
- (nonnull NSDate *)getTime;

@end
