// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#import "LGEthereumLikeNetworkParameters.h"


@implementation LGEthereumLikeNetworkParameters

- (nonnull instancetype)initWithIdentifier:(nonnull NSString *)Identifier
                             MessagePrefix:(nonnull NSString *)MessagePrefix
                               XPUBVersion:(nonnull NSData *)XPUBVersion
                            AdditionalEIPs:(nonnull NSArray<NSString *> *)AdditionalEIPs
{
    if (self = [super init]) {
        _Identifier = [Identifier copy];
        _MessagePrefix = [MessagePrefix copy];
        _XPUBVersion = [XPUBVersion copy];
        _AdditionalEIPs = [AdditionalEIPs copy];
    }
    return self;
}

+ (nonnull instancetype)EthereumLikeNetworkParametersWithIdentifier:(nonnull NSString *)Identifier
                                                      MessagePrefix:(nonnull NSString *)MessagePrefix
                                                        XPUBVersion:(nonnull NSData *)XPUBVersion
                                                     AdditionalEIPs:(nonnull NSArray<NSString *> *)AdditionalEIPs
{
    return [[self alloc] initWithIdentifier:Identifier
                              MessagePrefix:MessagePrefix
                                XPUBVersion:XPUBVersion
                             AdditionalEIPs:AdditionalEIPs];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p Identifier:%@ MessagePrefix:%@ XPUBVersion:%@ AdditionalEIPs:%@>", self.class, (void *)self, self.Identifier, self.MessagePrefix, self.XPUBVersion, self.AdditionalEIPs];
}

@end
