// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networks.djinni

#import "LGBitcoinLikeNetworkParameters.h"
#import "LGEthereumLikeNetworkParameters.h"
#import <Foundation/Foundation.h>


@interface LGNetworks : NSObject

+ (nonnull LGBitcoinLikeNetworkParameters *)bitcoin;

+ (nonnull LGEthereumLikeNetworkParameters *)ethereum;

@end
