// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGEthereumLikeOperation.h"
#import "LGEthereumLikeTransaction.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class representing a Ethereum Operation */
@interface RCTCoreLGEthereumLikeOperation : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEthereumLikeOperation *objcImpl;
@end
