// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#import "LGEthereumLikeAddress.h"
#import "LGEthereumLikeNetworkParameters.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/** Helper class for manipulating Ethereum like addresses */
@interface RCTCoreLGEthereumLikeAddress : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEthereumLikeAddress *objcImpl;
@end
