// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGEthereumLikeBlock.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class representing Bitcoin block */
@interface RCTCoreLGEthereumLikeBlock : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEthereumLikeBlock *objcImpl;
@end
