// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "RCTCoreLGEthereumLikeAccount.h"


@implementation RCTCoreLGEthereumLikeAccount
//Export module
RCT_EXPORT_MODULE(RCTCoreLGEthereumLikeAccount)

-(instancetype)init
{
    self = [super init];
    //Init Objc implementation
    if(self)
    {
        self.objcImpl = [[LGEthereumLikeAccount alloc] init];
    }
    return self;
}

RCT_REMAP_METHOD(broadcastRawTransaction,broadcastRawTransaction:(nonnull NSData *)transaction
                                                        callback:(nullable id<LGStringCallback>)callback) {

    [self.objcImpl broadcastRawTransaction:transaction callback:callback];
}

RCT_REMAP_METHOD(broadcastTransaction,broadcastTransaction:(nullable LGEthereumLikeTransaction *)transaction
                                                  callback:(nullable id<LGStringCallback>)callback) {

    [self.objcImpl broadcastTransaction:transaction callback:callback];
}

RCT_REMAP_METHOD(buildTransaction,buildTransactionWithResolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {

    id result = @{@"result" :[self.objcImpl buildTransaction]};
    if(result)
    {
        resolve(result);
    }
    else
    {
        reject(@"impl_call_error", @"Error while calling LGEthereumLikeAccount::buildTransaction", nil);
    }
}
@end
