// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#import "LGError.h"
#import "LGEthereumLikeTransaction.h"
#import "LGEthereumLikeTransactionCallbackImpl.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**
 *Callback triggered by main completed task,
 *returns optional result of template type T
 */
@interface RCTCoreLGEthereumLikeTransactionCallback : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEthereumLikeTransactionCallbackImpl *objcImpl;
@end
