// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGEthereumLikeAccount.h"
#import "LGEthereumLikeTransaction.h"
#import "LGEthereumLikeTransactionBuilder.h"
#import "LGStringCallback.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class representing a Ethereum account */
@interface RCTCoreLGEthereumLikeAccount : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEthereumLikeAccount *objcImpl;
@end
