// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGAmount.h"
#import "LGEthereumLikeAddress.h"
#import "LGEthereumLikeTransaction.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class representing a Ethereum transaction */
@interface RCTCoreLGEthereumLikeTransaction : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEthereumLikeTransaction *objcImpl;
@end
