// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGAmount.h"
#import "LGCurrency.h"
#import "LGEthereumLikeTransaction.h"
#import "LGEthereumLikeTransactionBuilder.h"
#import "LGEthereumLikeTransactionCallback.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


@interface RCTCoreLGEthereumLikeTransactionBuilder : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEthereumLikeTransactionBuilder *objcImpl;
@end
