// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#import "LGEthereumLikeAddress.h"
#import "LGEthereumLikeExtendedPublicKey.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


@interface RCTCoreLGEthereumLikeExtendedPublicKey : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEthereumLikeExtendedPublicKey *objcImpl;
@end
