// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "RCTCoreLGEthereumLikeOperation.h"


@implementation RCTCoreLGEthereumLikeOperation
//Export module
RCT_EXPORT_MODULE(RCTCoreLGEthereumLikeOperation)

-(instancetype)init
{
    self = [super init];
    //Init Objc implementation
    if(self)
    {
        self.objcImpl = [[LGEthereumLikeOperation alloc] init];
    }
    return self;
}

/**
 *Get operation's transaction
 *@return EthereumLikeTransaction object
 */
RCT_REMAP_METHOD(getTransaction,getTransactionWithResolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {

    id result = @{@"result" :[self.objcImpl getTransaction]};
    if(result)
    {
        resolve(result);
    }
    else
    {
        reject(@"impl_call_error", @"Error while calling LGEthereumLikeOperation::getTransaction", nil);
    }
}
@end
