// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from erc20.djinni

#include "ERC20LikeTransaction.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGERC20LikeTransaction;

namespace djinni_generated {

class ERC20LikeTransaction
{
public:
    using CppType = std::shared_ptr<::ledger::core::api::ERC20LikeTransaction>;
    using CppOptType = std::shared_ptr<::ledger::core::api::ERC20LikeTransaction>;
    using ObjcType = LGERC20LikeTransaction*;

    using Boxed = ERC20LikeTransaction;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

