// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#import "LGEthereumLikeNetworkParameters+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto EthereumLikeNetworkParameters::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.Identifier),
            ::djinni::String::toCpp(obj.MessagePrefix),
            ::djinni::Binary::toCpp(obj.XPUBVersion),
            ::djinni::List<::djinni::String>::toCpp(obj.AdditionalEIPs)};
}

auto EthereumLikeNetworkParameters::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LGEthereumLikeNetworkParameters alloc] initWithIdentifier:(::djinni::String::fromCpp(cpp.Identifier))
                                                         MessagePrefix:(::djinni::String::fromCpp(cpp.MessagePrefix))
                                                           XPUBVersion:(::djinni::Binary::fromCpp(cpp.XPUBVersion))
                                                        AdditionalEIPs:(::djinni::List<::djinni::String>::fromCpp(cpp.AdditionalEIPs))];
}

}  // namespace djinni_generated
