// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from erc20.djinni

#ifndef DJINNI_GENERATED_NJSERC20LIKETRANSACTION_HPP
#define DJINNI_GENERATED_NJSERC20LIKETRANSACTION_HPP


#include "NJSAmountCpp.hpp"
#include "NJSEthereumLikeAddressCpp.hpp"
#include <chrono>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include <nan.h>
#include <node.h>
#include "../../../core/src/api/ERC20LikeTransaction.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSERC20LikeTransaction: public Nan::ObjectWrap {
public:

    static void Initialize(Local<Object> target);
    virtual ~NJSERC20LikeTransaction() {};
    NJSERC20LikeTransaction(const std::shared_ptr<ledger::core::api::ERC20LikeTransaction> &iERC20LikeTransaction):_ERC20LikeTransaction(iERC20LikeTransaction){};

    static Handle<Object> wrap(const std::shared_ptr<ledger::core::api::ERC20LikeTransaction> &object);
    static Nan::Persistent<ObjectTemplate> ERC20LikeTransaction_prototype;
    std::shared_ptr<ledger::core::api::ERC20LikeTransaction> getCppImpl(){return _ERC20LikeTransaction;};

private:
    /** Get the hash of the transaction. */
    static NAN_METHOD(getHash);

    /** Get the nonce of the transaction : sequence number issued by originating EOA */
    static NAN_METHOD(getNonce);

    /** Get Gas price (in wei) */
    static NAN_METHOD(getGasPrice);

    /** Get start gas (in wei) : maximum amount of gas the originator is willing to pay */
    static NAN_METHOD(getGasLimit);

    /** Used gas (in wei) : used gas during this transaction */
    static NAN_METHOD(getUsedLimit);

    /** Get source ETH address */
    static NAN_METHOD(getSender);

    /** Get destination ETH address */
    static NAN_METHOD(getReceiver);

    /** Get amount of ether to send */
    static NAN_METHOD(getValue);

    /** Get binary data payload */
    static NAN_METHOD(getData);

    /**
     * Get the time when the transaction was issued or the time of the block including
     * this transaction
     */
    static NAN_METHOD(getTime);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
    std::shared_ptr<ledger::core::api::ERC20LikeTransaction> _ERC20LikeTransaction;
};
#endif //DJINNI_GENERATED_NJSERC20LIKETRANSACTION_HPP
