// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

#ifndef DJINNI_GENERATED_NJSETHEREUMLIKEADDRESS_HPP
#define DJINNI_GENERATED_NJSETHEREUMLIKEADDRESS_HPP


#include "../../../core/src/api/EthereumLikeNetworkParameters.hpp"
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include <nan.h>
#include <node.h>
#include "../../../core/src/api/EthereumLikeAddress.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSEthereumLikeAddress: public Nan::ObjectWrap {
public:

    static void Initialize(Local<Object> target);
    virtual ~NJSEthereumLikeAddress() {};
    NJSEthereumLikeAddress(const std::shared_ptr<ledger::core::api::EthereumLikeAddress> &iEthereumLikeAddress):_EthereumLikeAddress(iEthereumLikeAddress){};

    static Handle<Object> wrap(const std::shared_ptr<ledger::core::api::EthereumLikeAddress> &object);
    static Nan::Persistent<ObjectTemplate> EthereumLikeAddress_prototype;
    std::shared_ptr<ledger::core::api::EthereumLikeAddress> getCppImpl(){return _EthereumLikeAddress;};

private:
    /**
     * Gets the version of the address
     * @return The version of the address
     */
    static NAN_METHOD(getVersion);

    /**
     * Gets the raw hash160 of the public key
     * @return The 20 bytes of the public key hash160
     */
    static NAN_METHOD(getHash160);

    /**
     * Gets the network parameters used for serializing the address
     * @return The network parameters of the address
     */
    static NAN_METHOD(getNetworkParameters);

    /**
     * Serializes the hash160 into a Base58 encoded address (with checksum)
     * @return The Base58 serialization
     */
    static NAN_METHOD(toBase58);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
    std::shared_ptr<ledger::core::api::EthereumLikeAddress> _EthereumLikeAddress;
};
#endif //DJINNI_GENERATED_NJSETHEREUMLIKEADDRESS_HPP
