// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#ifndef DJINNI_GENERATED_NJSETHEREUMLIKEOPERATION_HPP
#define DJINNI_GENERATED_NJSETHEREUMLIKEOPERATION_HPP


#include "NJSEthereumLikeTransactionCpp.hpp"
#include <memory>

#include <nan.h>
#include <node.h>
#include "../../../core/src/api/EthereumLikeOperation.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSEthereumLikeOperation: public Nan::ObjectWrap {
public:

    static void Initialize(Local<Object> target);
    virtual ~NJSEthereumLikeOperation() {};
    NJSEthereumLikeOperation(const std::shared_ptr<ledger::core::api::EthereumLikeOperation> &iEthereumLikeOperation):_EthereumLikeOperation(iEthereumLikeOperation){};

    static Handle<Object> wrap(const std::shared_ptr<ledger::core::api::EthereumLikeOperation> &object);
    static Nan::Persistent<ObjectTemplate> EthereumLikeOperation_prototype;
    std::shared_ptr<ledger::core::api::EthereumLikeOperation> getCppImpl(){return _EthereumLikeOperation;};

private:
    /**
     *Get operation's transaction
     *@return EthereumLikeTransaction object
     */
    static NAN_METHOD(getTransaction);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
    std::shared_ptr<ledger::core::api::EthereumLikeOperation> _EthereumLikeOperation;
};
#endif //DJINNI_GENERATED_NJSETHEREUMLIKEOPERATION_HPP
