// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from erc20.djinni

package co.ledger.core;

import java.util.Date;
import java.util.concurrent.atomic.AtomicBoolean;

/**Class representing a Ethereum transaction */
public abstract class ERC20LikeTransaction {
    /** Get the hash of the transaction. */
    public abstract String getHash();

    /** Get the nonce of the transaction : sequence number issued by originating EOA */
    public abstract int getNonce();

    /** Get Gas price (in wei) */
    public abstract Amount getGasPrice();

    /** Get start gas (in wei) : maximum amount of gas the originator is willing to pay */
    public abstract Amount getGasLimit();

    /** Used gas (in wei) : used gas during this transaction */
    public abstract Amount getUsedLimit();

    /** Get source ETH address */
    public abstract EthereumLikeAddress getSender();

    /** Get destination ETH address */
    public abstract EthereumLikeAddress getReceiver();

    /** Get amount of ether to send */
    public abstract Amount getValue();

    /** Get binary data payload */
    public abstract byte[] getData();

    /**
     * Get the time when the transaction was issued or the time of the block including
     * this transaction
     */
    public abstract Date getTime();

    private static final class CppProxy extends ERC20LikeTransaction
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String getHash()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getHash(this.nativeRef);
        }
        private native String native_getHash(long _nativeRef);

        @Override
        public int getNonce()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getNonce(this.nativeRef);
        }
        private native int native_getNonce(long _nativeRef);

        @Override
        public Amount getGasPrice()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGasPrice(this.nativeRef);
        }
        private native Amount native_getGasPrice(long _nativeRef);

        @Override
        public Amount getGasLimit()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGasLimit(this.nativeRef);
        }
        private native Amount native_getGasLimit(long _nativeRef);

        @Override
        public Amount getUsedLimit()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getUsedLimit(this.nativeRef);
        }
        private native Amount native_getUsedLimit(long _nativeRef);

        @Override
        public EthereumLikeAddress getSender()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getSender(this.nativeRef);
        }
        private native EthereumLikeAddress native_getSender(long _nativeRef);

        @Override
        public EthereumLikeAddress getReceiver()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getReceiver(this.nativeRef);
        }
        private native EthereumLikeAddress native_getReceiver(long _nativeRef);

        @Override
        public Amount getValue()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getValue(this.nativeRef);
        }
        private native Amount native_getValue(long _nativeRef);

        @Override
        public byte[] getData()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getData(this.nativeRef);
        }
        private native byte[] native_getData(long _nativeRef);

        @Override
        public Date getTime()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getTime(this.nativeRef);
        }
        private native Date native_getTime(long _nativeRef);
    }
}
